linters:
  enable-all: true
  disable:
    - exhaustivestruct # deprecated
    - gochecknoglobals
    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - ifshort # deprecated
    - tagliatelle # Breaking: 'Rule' tag -> 'rule'
    - varnamelen # useless

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - exhaustivestruct
        - exhaustruct

linters-settings:
  cyclop:
    max-complexity: 11
